import type { UserProfile } from './types';


const profiles: UserProfile[] = [
  {
    id: '1', name: 'Zara', age: 29, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Live laugh lip sync',
    bio: 'City girl with a country heart. Love brunch and long walks to the fridge.',
    distance: '1.9 mi', lastActive: '5m ago', verified: true, online: false,
    lat: 40.7574, lng: -73.9679,
    photos: ['https://randomuser.me/api/portraits/women/1.jpg', 'https://randomuser.me/api/portraits/women/2.jpg', 'https://randomuser.me/api/portraits/women/3.jpg'],
    height: '4ft 10in', bodyType: 'Average', ethnicity: 'Mixed',
    lookingFor: ['Friends', 'Right Now', 'Networking'],
    interests: ['Cosplay', 'Fashion', 'Writing', 'Boxing', 'Camping'],
  },
  {
    id: '2', name: 'Maya', age: 28, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Soft boi energy',
    bio: 'Art student by day, DJ by night. I make playlists for every mood.',
    distance: '4.1 mi', lastActive: '30m ago', verified: true, online: false,
    lat: 40.7469, lng: -73.9737,
    photos: ['https://randomuser.me/api/portraits/women/4.jpg', 'https://randomuser.me/api/portraits/women/5.jpg', 'https://randomuser.me/api/portraits/women/6.jpg'],
    height: '4ft 11in', bodyType: 'Full-figured', ethnicity: 'Other',
    lookingFor: ['Relationship', 'Right Now', 'Chat'],
    interests: ['Music', 'Running', 'Craft Beer', 'Skateboarding'],
  },
  {
    id: '3', name: 'Jade', age: 28, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Bookworm with a wild side',
    bio: 'PhD student. I will steal your fries and your heart.',
    distance: '0.1 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7296, lng: -74.0081,
    photos: ['https://randomuser.me/api/portraits/women/7.jpg', 'https://randomuser.me/api/portraits/women/8.jpg'],
    height: '6ft 5in', bodyType: 'Athletic', ethnicity: 'Other',
    lookingFor: ['Dates', 'Friends', 'Relationship'],
    interests: ['Craft Beer', 'Dancing', 'Hiking', 'Wine', 'Tech'],
  },
  {
    id: '4', name: 'Luna', age: 21, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Gym rat in denial',
    bio: 'Software engineer who goes outside sometimes. Dog dad.',
    distance: '0.5 mi', lastActive: '2h ago', verified: true, online: false,
    lat: 40.7543, lng: -73.9804,
    photos: ['https://randomuser.me/api/portraits/women/9.jpg', 'https://randomuser.me/api/portraits/women/10.jpg'],
    height: '6ft 5in', bodyType: 'Petite', ethnicity: 'Black',
    lookingFor: ['Right Now', 'Dates', 'Relationship'],
    interests: ['Fishing', 'Coffee', 'Sushi', 'Anime', 'Parties'],
  },
  {
    id: '5', name: 'Aria', age: 19, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Life of the party',
    bio: 'Event planner by trade, dance floor queen by passion.',
    distance: '1.8 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.7691, lng: -73.9695,
    photos: ['https://randomuser.me/api/portraits/women/11.jpg', 'https://randomuser.me/api/portraits/women/12.jpg'],
    height: '5ft 4in', bodyType: 'Slim', ethnicity: 'White',
    lookingFor: ['Relationship', 'Networking', 'Right Now', 'Chat'],
    interests: ['Skateboarding', 'Sushi', 'Dancing', 'Music', 'Tea'],
  },
  {
    id: '6', name: 'Celeste', age: 28, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Plant parent extraordinaire',
    bio: 'Environmental scientist with 47 houseplants.',
    distance: '1.5 mi', lastActive: '1m ago', verified: false, online: false,
    lat: 40.7379, lng: -74.023,
    photos: ['https://randomuser.me/api/portraits/women/13.jpg', 'https://randomuser.me/api/portraits/women/14.jpg', 'https://randomuser.me/api/portraits/women/15.jpg'],
    height: '5ft 8in', bodyType: 'Petite', ethnicity: 'Black',
    lookingFor: ['Friends', 'Dates', 'Relationship'],
    interests: ['Fitness', 'Cooking', 'Parties', 'Yoga', 'Martial Arts'],
  },
  {
    id: '7', name: 'Vivian', age: 29, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Goth gf energy',
    bio: 'Tattoo artist with a dark sense of humor.',
    distance: '4.2 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7008, lng: -74.0117,
    photos: ['https://randomuser.me/api/portraits/women/16.jpg', 'https://randomuser.me/api/portraits/women/17.jpg'],
    height: '6ft 0in', bodyType: 'Full-figured', ethnicity: 'Asian',
    lookingFor: ['Right Now', 'Chat', 'Friends'],
    interests: ['Movies', 'Coffee', 'Sushi', 'Hiking'],
  },
  {
    id: '8', name: 'Scarlett', age: 31, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Chaotic good alignment',
    bio: 'Barista who makes latte art too pretty to drink.',
    distance: '3.5 mi', lastActive: '1m ago', verified: false, online: false,
    lat: 40.711, lng: -73.9779,
    photos: ['https://randomuser.me/api/portraits/women/18.jpg', 'https://randomuser.me/api/portraits/women/19.jpg', 'https://randomuser.me/api/portraits/women/20.jpg'],
    height: '5ft 4in', bodyType: 'Slim', ethnicity: 'Black',
    lookingFor: ['Right Now', 'Dates', 'Networking', 'Chat'],
    interests: ['Wine', 'Brunch', 'Fishing', 'Baking', 'Fitness'],
  },
  {
    id: '9', name: 'Naomi', age: 31, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Dad jokes are my love language',
    bio: 'High school teacher. I make killer pancakes.',
    distance: '3.5 mi', lastActive: 'Yesterday', verified: true, online: false,
    lat: 40.7087, lng: -74.0599,
    photos: ['https://randomuser.me/api/portraits/women/21.jpg', 'https://randomuser.me/api/portraits/women/22.jpg', 'https://randomuser.me/api/portraits/women/23.jpg'],
    height: '6ft 2in', bodyType: 'Muscular', ethnicity: 'Mixed',
    lookingFor: ['Relationship', 'Friends', 'Dates'],
    interests: ['Poetry', 'Painting', 'Running'],
  },
  {
    id: '10', name: 'Destiny', age: 32, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Siren of the stage',
    bio: 'Pop singer working on my debut EP.',
    distance: '4.0 mi', lastActive: '1h ago', verified: true, online: false,
    lat: 40.6885, lng: -73.9617,
    photos: ['https://randomuser.me/api/portraits/women/24.jpg', 'https://randomuser.me/api/portraits/women/25.jpg', 'https://randomuser.me/api/portraits/women/26.jpg'],
    height: '5ft 5in', bodyType: 'Slim', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Networking', 'Chat', 'Friends'],
    interests: ['Skiing', 'Anime', 'Coffee', 'Kayaking', 'Cosplay'],
  },
  {
    id: '11', name: 'Serena', age: 19, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Speed demon',
    bio: 'Photography major, urban explorer.',
    distance: '4.4 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7815, lng: -73.9622,
    photos: ['https://randomuser.me/api/portraits/women/27.jpg', 'https://randomuser.me/api/portraits/women/28.jpg', 'https://randomuser.me/api/portraits/women/29.jpg'],
    height: '5ft 2in', bodyType: 'Full-figured', ethnicity: 'White',
    lookingFor: ['Relationship', 'Dates', 'Friends', 'Right Now'],
    interests: ['Art', 'DJing', 'Baking', 'Rock Climbing', 'Tea'],
  },
  {
    id: '12', name: 'Olivia', age: 18, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Wine and world traveler',
    bio: 'Consultant by day, foodie by night.',
    distance: '2.4 mi', lastActive: '3h ago', verified: false, online: false,
    lat: 40.7869, lng: -73.9404,
    photos: ['https://randomuser.me/api/portraits/women/30.jpg', 'https://randomuser.me/api/portraits/women/31.jpg', 'https://randomuser.me/api/portraits/women/32.jpg'],
    height: '5ft 6in', bodyType: 'Petite', ethnicity: 'Black',
    lookingFor: ['Dates', 'Friends'],
    interests: ['Pilates', 'Sushi', 'Dancing', 'Boxing', 'Cosplay'],
  },
  {
    id: '13', name: 'Bianca', age: 20, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Coffee snob',
    bio: 'Nurse who saves lives by day and the dance floor by night.',
    distance: '2.0 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7801, lng: -73.9763,
    photos: ['https://randomuser.me/api/portraits/women/33.jpg', 'https://randomuser.me/api/portraits/women/34.jpg', 'https://randomuser.me/api/portraits/women/35.jpg'],
    height: '4ft 10in', bodyType: 'Muscular', ethnicity: 'White',
    lookingFor: ['Relationship', 'Right Now', 'Networking'],
    interests: ['Dancing', 'Fitness', 'Tattoos'],
  },
  {
    id: '14', name: 'Tiffany', age: 21, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Certified nerd',
    bio: 'Baker extraordinaire. My sourdough has a name.',
    distance: '1.9 mi', lastActive: '1h ago', verified: false, online: false,
    lat: 40.7675, lng: -73.9485,
    photos: ['https://randomuser.me/api/portraits/women/36.jpg', 'https://randomuser.me/api/portraits/women/37.jpg', 'https://randomuser.me/api/portraits/women/38.jpg'],
    height: '5ft 6in', bodyType: 'Curvy', ethnicity: 'Asian',
    lookingFor: ['Friends', 'Chat'],
    interests: ['Cosplay', 'Gaming', 'Parties', 'Photography'],
  },
  {
    id: '15', name: 'Angel', age: 23, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Sunshine person',
    bio: 'Chef who believes food is the language of love.',
    distance: '1.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7312, lng: -73.9926,
    photos: ['https://randomuser.me/api/portraits/women/39.jpg', 'https://randomuser.me/api/portraits/women/40.jpg', 'https://randomuser.me/api/portraits/women/41.jpg'],
    height: '6ft 1in', bodyType: 'Curvy', ethnicity: 'Middle Eastern',
    lookingFor: ['Networking', 'Relationship'],
    interests: ['Surfing', 'Skateboarding', 'Dogs', 'Theater', 'Meditation'],
  },
  {
    id: '16', name: 'Vanessa', age: 22, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Night owl',
    bio: 'Startup founder building something that matters.',
    distance: '2.8 mi', lastActive: '15m ago', verified: true, online: false,
    lat: 40.7203, lng: -74.0174,
    photos: ['https://randomuser.me/api/portraits/women/42.jpg', 'https://randomuser.me/api/portraits/women/43.jpg'],
    height: '5ft 3in', bodyType: 'Slim', ethnicity: 'Other',
    lookingFor: ['Dates', 'Relationship', 'Friends', 'Networking'],
    interests: ['Karaoke', 'Cooking', 'Fitness', 'Rock Climbing'],
  },
  {
    id: '17', name: 'Diana', age: 22, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Dog mom',
    bio: 'Librarian by day, DJ by night.',
    distance: '2.4 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.7431, lng: -73.7845,
    photos: ['https://randomuser.me/api/portraits/women/44.jpg', 'https://randomuser.me/api/portraits/women/45.jpg'],
    height: '5ft 4in', bodyType: 'Muscular', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Chat', 'Dates', 'Relationship', 'Networking'],
    interests: ['Kayaking', 'Fitness', 'Dancing', 'Yoga', 'Fishing'],
  },
  {
    id: '18', name: 'Crystal', age: 26, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Cat person purrr',
    bio: 'Yoga instructor finding peace one pose at a time.',
    distance: '4.1 mi', lastActive: '15m ago', verified: true, online: false,
    lat: 40.7263, lng: -73.9958,
    photos: ['https://randomuser.me/api/portraits/women/46.jpg', 'https://randomuser.me/api/portraits/women/47.jpg', 'https://randomuser.me/api/portraits/women/48.jpg'],
    height: '5ft 0in', bodyType: 'Full-figured', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Relationship', 'Networking', 'Dates'],
    interests: ['Fashion', 'Cats', 'Movies', 'Rock Climbing', 'Foodie'],
  },
  {
    id: '19', name: 'Kiana', age: 20, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Foodie for life',
    bio: 'Writer working on my first novel.',
    distance: '3.3 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7468, lng: -73.9779,
    photos: ['https://randomuser.me/api/portraits/women/49.jpg', 'https://randomuser.me/api/portraits/women/50.jpg', 'https://randomuser.me/api/portraits/women/51.jpg'],
    height: '5ft 7in', bodyType: 'Muscular', ethnicity: 'White',
    lookingFor: ['Networking', 'Friends', 'Dates'],
    interests: ['Fashion', 'Music', 'DJing'],
  },
  {
    id: '20', name: 'Indigo', age: 29, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Adventure awaits',
    bio: 'Graphic designer with a passion for queer art.',
    distance: '4.4 mi', lastActive: '3h ago', verified: true, online: false,
    lat: 40.7732, lng: -73.9716,
    photos: ['https://randomuser.me/api/portraits/women/52.jpg', 'https://randomuser.me/api/portraits/women/53.jpg'],
    height: '5ft 0in', bodyType: 'Full-figured', ethnicity: 'Asian',
    lookingFor: ['Dates', 'Networking', 'Right Now', 'Friends'],
    interests: ['Boxing', 'Kayaking', 'Surfing', 'Sushi'],
  },
  {
    id: '21', name: 'Brianna', age: 28, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Beach bum',
    bio: 'Personal trainer who motivates and makes you laugh.',
    distance: '1.5 mi', lastActive: '5m ago', verified: true, online: false,
    lat: 40.7661, lng: -73.9833,
    photos: ['https://randomuser.me/api/portraits/women/54.jpg', 'https://randomuser.me/api/portraits/women/55.jpg', 'https://randomuser.me/api/portraits/women/56.jpg'],
    height: '6ft 3in', bodyType: 'Petite', ethnicity: 'Mixed',
    lookingFor: ['Dates', 'Friends', 'Chat'],
    interests: ['Dogs', 'Tattoos', 'Fitness', 'Music'],
  },
  {
    id: '22', name: 'Kamila', age: 25, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'City kid',
    bio: 'Social worker changing the world one person at a time.',
    distance: '1.6 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7878, lng: -73.9625,
    photos: ['https://randomuser.me/api/portraits/women/57.jpg', 'https://randomuser.me/api/portraits/women/58.jpg', 'https://randomuser.me/api/portraits/women/59.jpg'],
    height: '5ft 11in', bodyType: 'Average', ethnicity: 'White',
    lookingFor: ['Chat', 'Relationship', 'Networking', 'Friends'],
    interests: ['Baking', 'Art', 'Cooking'],
  },
  {
    id: '23', name: 'Riley W', age: 20, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Yoga every day',
    bio: 'DJ spinning beats that make your soul dance.',
    distance: '0.2 mi', lastActive: '2h ago', verified: false, online: false,
    lat: 40.7606, lng: -73.9798,
    photos: ['https://randomuser.me/api/portraits/women/60.jpg', 'https://randomuser.me/api/portraits/women/61.jpg', 'https://randomuser.me/api/portraits/women/62.jpg'],
    height: '6ft 1in', bodyType: 'Average', ethnicity: 'Mixed',
    lookingFor: ['Friends', 'Dates', 'Right Now'],
    interests: ['Painting', 'Karaoke', 'Dancing', 'Baking', 'Yoga'],
  },
  {
    id: '24', name: 'Morgan T', age: 25, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Music is life',
    bio: 'Therapist helping people find their inner light.',
    distance: '3.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7509, lng: -73.9827,
    photos: ['https://randomuser.me/api/portraits/women/63.jpg', 'https://randomuser.me/api/portraits/women/64.jpg', 'https://randomuser.me/api/portraits/women/65.jpg'],
    height: '5ft 4in', bodyType: 'Petite', ethnicity: 'Asian',
    lookingFor: ['Dates', 'Right Now', 'Chat'],
    interests: ['Dancing', 'Meditation', 'Kayaking', 'Foodie'],
  },
  {
    id: '25', name: 'Destiny F', age: 31, pronouns: 'she/her',
    identity: 'Trans Woman',
    tagline: 'Art lover',
    bio: 'Scientist with glitter in my hair.',
    distance: '3.3 mi', lastActive: '30m ago', verified: true, online: false,
    lat: 40.7263, lng: -73.9934,
    photos: ['https://randomuser.me/api/portraits/women/66.jpg', 'https://randomuser.me/api/portraits/women/67.jpg', 'https://randomuser.me/api/portraits/women/68.jpg'],
    height: '5ft 4in', bodyType: 'Petite', ethnicity: 'Mixed',
    lookingFor: ['Friends', 'Dates', 'Chat', 'Relationship'],
    interests: ['Writing', 'Fitness', 'Pilates', 'Tattoos', 'Skateboarding'],
  },
  {
    id: '26', name: 'Kai', age: 23, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Tech geek',
    bio: 'Firefighter who rescues cats and hearts.',
    distance: '3.0 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7338, lng: -74.0066,
    photos: ['https://randomuser.me/api/portraits/men/1.jpg', 'https://randomuser.me/api/portraits/men/2.jpg'],
    height: '5ft 10in', bodyType: 'Curvy', ethnicity: 'Other',
    lookingFor: ['Networking', 'Chat'],
    interests: ['Tattoos', 'Movies', 'Martial Arts', 'Skiing'],
  },
  {
    id: '27', name: 'Dylan', age: 31, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Bookworm',
    bio: 'Pilot who has been everywhere but still looking for home.',
    distance: '1.6 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7074, lng: -74.0061,
    photos: ['https://randomuser.me/api/portraits/men/3.jpg', 'https://randomuser.me/api/portraits/men/4.jpg', 'https://randomuser.me/api/portraits/men/5.jpg'],
    height: '5ft 9in', bodyType: 'Muscular', ethnicity: 'Asian',
    lookingFor: ['Networking', 'Relationship', 'Right Now', 'Chat'],
    interests: ['Painting', 'Photography', 'Movies', 'Camping', 'Anime'],
  },
  {
    id: '28', name: 'Ren', age: 19, pronouns: 'he/they',
    identity: 'Trans Man',
    tagline: 'Movie buff',
    bio: 'Barber who gives the best conversations with every cut.',
    distance: '0.1 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.6805, lng: -74.0498,
    photos: ['https://randomuser.me/api/portraits/men/6.jpg', 'https://randomuser.me/api/portraits/men/7.jpg'],
    height: '5ft 8in', bodyType: 'Curvy', ethnicity: 'White',
    lookingFor: ['Relationship', 'Friends', 'Chat', 'Right Now'],
    interests: ['Hiking', 'Poetry', 'Meditation', 'Martial Arts', 'Kayaking'],
  },
  {
    id: '29', name: 'Ezra', age: 21, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Home chef',
    bio: 'Journalist telling stories that need to be heard.',
    distance: '2.7 mi', lastActive: '30m ago', verified: false, online: false,
    lat: 40.6307, lng: -73.9511,
    photos: ['https://randomuser.me/api/portraits/men/8.jpg', 'https://randomuser.me/api/portraits/men/9.jpg'],
    height: '4ft 10in', bodyType: 'Muscular', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Dates', 'Relationship', 'Friends'],
    interests: ['Cats', 'Tech', 'Skiing', 'Art', 'Meditation'],
  },
  {
    id: '30', name: 'Marcus', age: 21, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Photographer',
    bio: 'Astronomy nerd looking for my star alignment.',
    distance: '4.5 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.5639, lng: -73.9789,
    photos: ['https://randomuser.me/api/portraits/men/10.jpg', 'https://randomuser.me/api/portraits/men/11.jpg', 'https://randomuser.me/api/portraits/men/12.jpg'],
    height: '6ft 4in', bodyType: 'Athletic', ethnicity: 'Black',
    lookingFor: ['Dates', 'Friends', 'Networking', 'Chat'],
    interests: ['Martial Arts', 'Craft Beer', 'Anime', 'DJing'],
  },
  {
    id: '31', name: 'Jordan M', age: 23, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Free spirit',
    bio: 'Botanical illustrator who sees beauty in every petal.',
    distance: '0.2 mi', lastActive: '30m ago', verified: true, online: false,
    lat: 40.6439, lng: -73.9473,
    photos: ['https://randomuser.me/api/portraits/men/13.jpg', 'https://randomuser.me/api/portraits/men/14.jpg', 'https://randomuser.me/api/portraits/men/15.jpg'],
    height: '5ft 11in', bodyType: 'Full-figured', ethnicity: 'White',
    lookingFor: ['Right Now', 'Chat', 'Friends', 'Networking'],
    interests: ['Photography', 'Reading', 'Movies', 'Painting'],
  },
  {
    id: '32', name: 'Blake', age: 19, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Meditation lover',
    bio: 'Former figure skater, current ice cream enthusiast.',
    distance: '3.1 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.6877, lng: -73.9926,
    photos: ['https://randomuser.me/api/portraits/men/16.jpg', 'https://randomuser.me/api/portraits/men/17.jpg', 'https://randomuser.me/api/portraits/men/18.jpg'],
    height: '5ft 0in', bodyType: 'Full-figured', ethnicity: 'Black',
    lookingFor: ['Chat', 'Right Now', 'Friends'],
    interests: ['Fitness', 'Fashion', 'Kayaking', 'Painting'],
  },
  {
    id: '33', name: 'Cameron', age: 28, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Dancer',
    bio: 'Yoga teacher and former wrestler.',
    distance: '0.7 mi', lastActive: '30m ago', verified: true, online: false,
    lat: 40.7706, lng: -73.9673,
    photos: ['https://randomuser.me/api/portraits/men/19.jpg', 'https://randomuser.me/api/portraits/men/20.jpg'],
    height: '5ft 8in', bodyType: 'Muscular', ethnicity: 'Middle Eastern',
    lookingFor: ['Friends', 'Chat'],
    interests: ['Cats', 'Karaoke', 'DJing', 'Brunch', 'Photography'],
  },
  {
    id: '34', name: 'Finn', age: 30, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Singer',
    bio: 'Tour guide who knows every hidden gem.',
    distance: '1.1 mi', lastActive: '30m ago', verified: true, online: false,
    lat: 40.7243, lng: -73.9795,
    photos: ['https://randomuser.me/api/portraits/men/21.jpg', 'https://randomuser.me/api/portraits/men/22.jpg', 'https://randomuser.me/api/portraits/men/23.jpg'],
    height: '4ft 10in', bodyType: 'Slim', ethnicity: 'Asian',
    lookingFor: ['Chat', 'Networking', 'Relationship'],
    interests: ['Dancing', 'Parties', 'Rock Climbing', 'Tattoos'],
  },
  {
    id: '35', name: 'Aiden', age: 28, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Writer',
    bio: 'Chaotic neutral energy with a heart of gold.',
    distance: '1.1 mi', lastActive: '1m ago', verified: true, online: false,
    lat: 40.7516, lng: -73.9901,
    photos: ['https://randomuser.me/api/portraits/men/24.jpg', 'https://randomuser.me/api/portraits/men/25.jpg'],
    height: '5ft 6in', bodyType: 'Full-figured', ethnicity: 'Mixed',
    lookingFor: ['Chat', 'Dates'],
    interests: ['Movies', 'Fitness', 'Camping', 'Cooking', 'Writing'],
  },
  {
    id: '36', name: 'Leo', age: 26, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Dreamer',
    bio: 'Ceramic artist making beautiful things with my hands.',
    distance: '4.0 mi', lastActive: '15m ago', verified: false, online: false,
    lat: 40.7697, lng: -73.9582,
    photos: ['https://randomuser.me/api/portraits/men/26.jpg', 'https://randomuser.me/api/portraits/men/27.jpg', 'https://randomuser.me/api/portraits/men/28.jpg'],
    height: '6ft 2in', bodyType: 'Curvy', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Friends', 'Chat'],
    interests: ['Fishing', 'Fitness', 'Baking', 'Running', 'Skateboarding'],
  },
  {
    id: '37', name: 'Theo', age: 20, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Healer',
    bio: 'Swim coach who makes waves.',
    distance: '4.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7976, lng: -73.9698,
    photos: ['https://randomuser.me/api/portraits/men/29.jpg', 'https://randomuser.me/api/portraits/men/30.jpg', 'https://randomuser.me/api/portraits/men/31.jpg'],
    height: '5ft 4in', bodyType: 'Curvy', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Relationship', 'Chat'],
    interests: ['Writing', 'Poetry', 'Skiing'],
  },
  {
    id: '38', name: 'Miles', age: 19, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Rebel with a cause',
    bio: 'Radio host with a voice for midnight.',
    distance: '0.6 mi', lastActive: '1m ago', verified: true, online: false,
    lat: 40.7674, lng: -73.9684,
    photos: ['https://randomuser.me/api/portraits/men/32.jpg', 'https://randomuser.me/api/portraits/men/33.jpg'],
    height: '5ft 8in', bodyType: 'Slim', ethnicity: 'Mixed',
    lookingFor: ['Relationship', 'Dates', 'Friends'],
    interests: ['Sushi', 'Gaming', 'DJing'],
  },
  {
    id: '39', name: 'Rowan R', age: 25, pronouns: 'he/they',
    identity: 'Trans Man',
    tagline: 'Empress energy',
    bio: 'Sommelier who knows wine and vibes.',
    distance: '4.2 mi', lastActive: '3h ago', verified: true, online: false,
    lat: 40.7521, lng: -73.9971,
    photos: ['https://randomuser.me/api/portraits/men/34.jpg', 'https://randomuser.me/api/portraits/men/35.jpg', 'https://randomuser.me/api/portraits/men/36.jpg'],
    height: '5ft 8in', bodyType: 'Athletic', ethnicity: 'Other',
    lookingFor: ['Dates', 'Chat', 'Networking', 'Friends'],
    interests: ['Theater', 'Swimming', 'Fishing', 'Running'],
  },
  {
    id: '40', name: 'Sam', age: 24, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Chaos agent',
    bio: 'Dance instructor who makes everyone feel like a star.',
    distance: '2.9 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.74, lng: -73.9668,
    photos: ['https://randomuser.me/api/portraits/men/37.jpg', 'https://randomuser.me/api/portraits/men/38.jpg', 'https://randomuser.me/api/portraits/men/39.jpg'],
    height: '5ft 6in', bodyType: 'Full-figured', ethnicity: 'Asian',
    lookingFor: ['Networking', 'Dates', 'Friends'],
    interests: ['Craft Beer', 'Tattoos', 'Fitness'],
  },
  {
    id: '41', name: 'Asher', age: 26, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Soft but fierce',
    bio: 'Massage therapist with healing hands.',
    distance: '2.6 mi', lastActive: '1m ago', verified: false, online: false,
    lat: 40.7396, lng: -74.0034,
    photos: ['https://randomuser.me/api/portraits/men/40.jpg', 'https://randomuser.me/api/portraits/men/41.jpg'],
    height: '6ft 1in', bodyType: 'Athletic', ethnicity: 'Asian',
    lookingFor: ['Chat', 'Relationship', 'Right Now'],
    interests: ['Dancing', 'DJing', 'Tea', 'Music', 'Photography'],
  },
  {
    id: '42', name: 'Dominic', age: 27, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Fluent in sarcasm',
    bio: 'Personal chef cooking love into every meal.',
    distance: '2.7 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7534, lng: -73.994,
    photos: ['https://randomuser.me/api/portraits/men/42.jpg', 'https://randomuser.me/api/portraits/men/43.jpg', 'https://randomuser.me/api/portraits/men/44.jpg'],
    height: '5ft 1in', bodyType: 'Athletic', ethnicity: 'White',
    lookingFor: ['Chat', 'Dates'],
    interests: ['Boxing', 'Meditation', 'Baking'],
  },
  {
    id: '43', name: 'Jude', age: 29, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Professional overthinker',
    bio: 'Dog trainer who listens better than most people.',
    distance: '4.2 mi', lastActive: '15m ago', verified: true, online: false,
    lat: 40.7254, lng: -73.9761,
    photos: ['https://randomuser.me/api/portraits/men/45.jpg', 'https://randomuser.me/api/portraits/men/46.jpg', 'https://randomuser.me/api/portraits/men/47.jpg'],
    height: '6ft 0in', bodyType: 'Full-figured', ethnicity: 'Other',
    lookingFor: ['Relationship', 'Networking', 'Right Now'],
    interests: ['Dogs', 'Hiking', 'Pilates', 'Kayaking'],
  },
  {
    id: '44', name: 'Silas', age: 27, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Snack enthusiast',
    bio: 'Bookstore owner surrounded by stories.',
    distance: '3.5 mi', lastActive: '1m ago', verified: true, online: false,
    lat: 40.7529, lng: -73.9713,
    photos: ['https://randomuser.me/api/portraits/men/48.jpg', 'https://randomuser.me/api/portraits/men/49.jpg'],
    height: '6ft 3in', bodyType: 'Curvy', ethnicity: 'Black',
    lookingFor: ['Right Now', 'Dates', 'Friends', 'Chat'],
    interests: ['DJing', 'Gaming', 'Fitness', 'Yoga', 'Travel'],
  },
  {
    id: '45', name: 'Elliot', age: 32, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Recovering perfectionist',
    bio: 'Music teacher who believes everyone deserves to sing.',
    distance: '1.3 mi', lastActive: '5m ago', verified: false, online: false,
    lat: 40.772, lng: -73.9628,
    photos: ['https://randomuser.me/api/portraits/men/50.jpg', 'https://randomuser.me/api/portraits/men/51.jpg'],
    height: '5ft 0in', bodyType: 'Curvy', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Dates', 'Friends', 'Networking'],
    interests: ['Coffee', 'Fitness', 'Foodie', 'Kayaking', 'Fishing'],
  },
  {
    id: '46', name: 'Nico N', age: 29, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Vibe curator',
    bio: 'Veterinarian in training. My patients are furry.',
    distance: '4.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7493, lng: -73.9943,
    photos: ['https://randomuser.me/api/portraits/men/52.jpg', 'https://randomuser.me/api/portraits/men/53.jpg'],
    height: '6ft 2in', bodyType: 'Curvy', ethnicity: 'White',
    lookingFor: ['Right Now', 'Friends'],
    interests: ['Brunch', 'Gaming', 'Cooking'],
  },
  {
    id: '47', name: 'Remy', age: 32, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Emotional support human',
    bio: 'Social media manager who actually goes outside.',
    distance: '3.0 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7373, lng: -74.0123,
    photos: ['https://randomuser.me/api/portraits/men/54.jpg', 'https://randomuser.me/api/portraits/men/55.jpg'],
    height: '5ft 7in', bodyType: 'Slim', ethnicity: 'White',
    lookingFor: ['Relationship', 'Dates', 'Friends', 'Chat'],
    interests: ['Poetry', 'Cosplay', 'Fishing'],
  },
  {
    id: '48', name: 'Shane', age: 28, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Certified delight',
    bio: 'Architect designing spaces where everyone belongs.',
    distance: '3.5 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7221, lng: -73.983,
    photos: ['https://randomuser.me/api/portraits/men/56.jpg', 'https://randomuser.me/api/portraits/men/57.jpg', 'https://randomuser.me/api/portraits/men/58.jpg'],
    height: '6ft 0in', bodyType: 'Curvy', ethnicity: 'Black',
    lookingFor: ['Right Now', 'Friends', 'Dates', 'Relationship'],
    interests: ['Hiking', 'Dogs', 'Writing', 'Foodie', 'Fashion'],
  },
  {
    id: '49', name: 'Koda', age: 20, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Main character energy',
    bio: 'Marine biologist who talks to fish.',
    distance: '2.3 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.6925, lng: -74.0503,
    photos: ['https://randomuser.me/api/portraits/men/59.jpg', 'https://randomuser.me/api/portraits/men/60.jpg'],
    height: '5ft 6in', bodyType: 'Average', ethnicity: 'Other',
    lookingFor: ['Networking', 'Dates'],
    interests: ['Writing', 'Art', 'Music', 'Anime'],
  },
  {
    id: '50', name: 'Caleb', age: 22, pronouns: 'he/him',
    identity: 'Trans Man',
    tagline: 'Unicorn',
    bio: 'Electrician who lights up rooms and spirits.',
    distance: '2.0 mi', lastActive: '15m ago', verified: false, online: false,
    lat: 40.6928, lng: -73.9276,
    photos: ['https://randomuser.me/api/portraits/men/61.jpg', 'https://randomuser.me/api/portraits/men/62.jpg', 'https://randomuser.me/api/portraits/men/63.jpg'],
    height: '5ft 1in', bodyType: 'Average', ethnicity: 'Asian',
    lookingFor: ['Dates', 'Friends', 'Right Now'],
    interests: ['Anime', 'Music', 'Fashion', 'Parties', 'Photography'],
  },
  {
    id: '51', name: 'Alex', age: 29, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Veggie lover',
    bio: 'City girl with a country heart. Love brunch and long walks to the fridge.',
    distance: '0.6 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7921, lng: -73.9835,
    photos: ['https://randomuser.me/api/portraits/women/69.jpg', 'https://randomuser.me/api/portraits/women/70.jpg'],
    height: '6ft 3in', bodyType: 'Muscular', ethnicity: 'Black',
    lookingFor: ['Friends', 'Right Now'],
    interests: ['Dogs', 'Tech', 'Cooking'],
  },
  {
    id: '52', name: 'Sage', age: 22, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Sunset chaser',
    bio: 'Art student by day, DJ by night. I make playlists for every mood.',
    distance: '1.3 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.772, lng: -73.9354,
    photos: ['https://randomuser.me/api/portraits/men/64.jpg', 'https://randomuser.me/api/portraits/men/65.jpg'],
    height: '5ft 11in', bodyType: 'Full-figured', ethnicity: 'Other',
    lookingFor: ['Right Now', 'Chat', 'Relationship'],
    interests: ['Surfing', 'Cats', 'Fashion'],
  },
  {
    id: '53', name: 'Quinn', age: 30, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Soul searchers',
    bio: 'PhD student. I will steal your fries and your heart.',
    distance: '2.1 mi', lastActive: '5m ago', verified: true, online: false,
    lat: 40.7803, lng: -73.9508,
    photos: ['https://randomuser.me/api/portraits/women/71.jpg', 'https://randomuser.me/api/portraits/women/72.jpg'],
    height: '5ft 3in', bodyType: 'Average', ethnicity: 'White',
    lookingFor: ['Dates', 'Chat'],
    interests: ['Meditation', 'DJing', 'Art'],
  },
  {
    id: '54', name: 'Avery', age: 18, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Dancing through life',
    bio: 'Software engineer who goes outside sometimes. Dog dad.',
    distance: '0.9 mi', lastActive: '1h ago', verified: false, online: false,
    lat: 40.7688, lng: -73.9846,
    photos: ['https://randomuser.me/api/portraits/men/66.jpg', 'https://randomuser.me/api/portraits/men/67.jpg'],
    height: '5ft 2in', bodyType: 'Petite', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Right Now'],
    interests: ['Cycling', 'Anime', 'Cats', 'Music'],
  },
  {
    id: '55', name: 'Harper', age: 22, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Wandering soul',
    bio: 'Event planner by trade, dance floor queen by passion.',
    distance: '2.8 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.7363, lng: -73.9744,
    photos: ['https://randomuser.me/api/portraits/women/73.jpg', 'https://randomuser.me/api/portraits/women/74.jpg'],
    height: '5ft 9in', bodyType: 'Petite', ethnicity: 'Asian',
    lookingFor: ['Dates', 'Friends', 'Chat'],
    interests: ['Art', 'Swimming', 'Brunch'],
  },
  {
    id: '56', name: 'Emery', age: 26, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Giggles guaranteed',
    bio: 'Environmental scientist with 47 houseplants.',
    distance: '4.4 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.7486, lng: -74.0097,
    photos: ['https://randomuser.me/api/portraits/men/68.jpg', 'https://randomuser.me/api/portraits/men/69.jpg'],
    height: '6ft 0in', bodyType: 'Muscular', ethnicity: 'White',
    lookingFor: ['Networking', 'Dates', 'Friends', 'Chat'],
    interests: ['Baking', 'Travel', 'Kayaking', 'Craft Beer'],
  },
  {
    id: '57', name: 'Dakota', age: 22, pronouns: 'any pronouns',
    identity: 'Genderfluid',
    tagline: 'Romantic at heart',
    bio: 'Tattoo artist with a dark sense of humor.',
    distance: '3.7 mi', lastActive: '3h ago', verified: true, online: false,
    lat: 40.7261, lng: -73.7993,
    photos: ['https://randomuser.me/api/portraits/women/75.jpg', 'https://randomuser.me/api/portraits/women/76.jpg'],
    height: '5ft 1in', bodyType: 'Average', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Right Now', 'Friends', 'Relationship'],
    interests: ['Tech', 'Cosplay', 'Theater'],
  },
  {
    id: '58', name: 'Skylar', age: 22, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Infinite vibes',
    bio: 'Barista who makes latte art too pretty to drink.',
    distance: '1.5 mi', lastActive: '15m ago', verified: false, online: false,
    lat: 40.7, lng: -73.9995,
    photos: ['https://randomuser.me/api/portraits/men/70.jpg', 'https://randomuser.me/api/portraits/men/71.jpg', 'https://randomuser.me/api/portraits/men/72.jpg'],
    height: '5ft 2in', bodyType: 'Athletic', ethnicity: 'Mixed',
    lookingFor: ['Relationship', 'Friends', 'Networking'],
    interests: ['Gaming', 'Reading', 'Foodie'],
  },
  {
    id: '59', name: 'Reese', age: 25, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Wildflower',
    bio: 'High school teacher. I make killer pancakes.',
    distance: '0.3 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7456, lng: -73.9989,
    photos: ['https://randomuser.me/api/portraits/women/77.jpg', 'https://randomuser.me/api/portraits/women/78.jpg'],
    height: '6ft 3in', bodyType: 'Full-figured', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Networking', 'Chat'],
    interests: ['Martial Arts', 'Dancing', 'Camping', 'Travel'],
  },
  {
    id: '60', name: 'Finley', age: 27, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Stardust child',
    bio: 'Pop singer working on my debut EP.',
    distance: '0.8 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.7598, lng: -73.9994,
    photos: ['https://randomuser.me/api/portraits/men/73.jpg', 'https://randomuser.me/api/portraits/men/74.jpg', 'https://randomuser.me/api/portraits/men/75.jpg'],
    height: '6ft 0in', bodyType: 'Slim', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Relationship'],
    interests: ['Fitness', 'Karaoke', 'Meditation', 'Dancing'],
  },
  {
    id: '61', name: 'Wren', age: 24, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Plant mom',
    bio: 'Photography major, urban explorer.',
    distance: '0.7 mi', lastActive: '15m ago', verified: false, online: false,
    lat: 40.7803, lng: -73.9582,
    photos: ['https://randomuser.me/api/portraits/women/79.jpg', 'https://randomuser.me/api/portraits/women/80.jpg'],
    height: '4ft 11in', bodyType: 'Full-figured', ethnicity: 'Middle Eastern',
    lookingFor: ['Chat', 'Friends'],
    interests: ['Cats', 'Travel', 'Running', 'Pilates'],
  },
  {
    id: '62', name: 'August', age: 20, pronouns: 'he/they',
    identity: 'Genderfluid',
    tagline: 'Coffee addict',
    bio: 'Consultant by day, foodie by night.',
    distance: '2.3 mi', lastActive: '2h ago', verified: false, online: false,
    lat: 40.766, lng: -73.942,
    photos: ['https://randomuser.me/api/portraits/men/76.jpg', 'https://randomuser.me/api/portraits/men/77.jpg'],
    height: '6ft 5in', bodyType: 'Slim', ethnicity: 'Other',
    lookingFor: ['Friends', 'Dates', 'Relationship', 'Right Now'],
    interests: ['Anime', 'Photography', 'Camping'],
  },
  {
    id: '63', name: 'River', age: 22, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Night market lover',
    bio: 'Nurse who saves lives by day and the dance floor by night.',
    distance: '3.1 mi', lastActive: '5m ago', verified: true, online: false,
    lat: 40.7552, lng: -73.9869,
    photos: ['https://randomuser.me/api/portraits/women/81.jpg', 'https://randomuser.me/api/portraits/women/82.jpg'],
    height: '5ft 7in', bodyType: 'Petite', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Dates', 'Right Now', 'Networking', 'Relationship'],
    interests: ['Dancing', 'Coffee', 'Craft Beer', 'Music'],
  },
  {
    id: '64', name: 'Blair', age: 19, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Sunshine and rainbows',
    bio: 'Baker extraordinaire. My sourdough has a name.',
    distance: '0.8 mi', lastActive: '15m ago', verified: true, online: false,
    lat: 40.7374, lng: -73.9635,
    photos: ['https://randomuser.me/api/portraits/men/78.jpg', 'https://randomuser.me/api/portraits/men/79.jpg', 'https://randomuser.me/api/portraits/men/80.jpg'],
    height: '5ft 11in', bodyType: 'Curvy', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Friends'],
    interests: ['Dancing', 'Tattoos', 'Kayaking', 'Running', 'Wine'],
  },
  {
    id: '65', name: 'Casey', age: 20, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Giggles and good vibes',
    bio: 'Chef who believes food is the language of love.',
    distance: '4.2 mi', lastActive: '30m ago', verified: false, online: false,
    lat: 40.7034, lng: -74.0038,
    photos: ['https://randomuser.me/api/portraits/women/83.jpg', 'https://randomuser.me/api/portraits/women/84.jpg', 'https://randomuser.me/api/portraits/women/85.jpg'],
    height: '6ft 4in', bodyType: 'Slim', ethnicity: 'Black',
    lookingFor: ['Relationship', 'Right Now'],
    interests: ['Cooking', 'Poetry', 'Hiking', 'Tea'],
  },
  {
    id: '66', name: 'Drew', age: 30, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Dancing queen',
    bio: 'Startup founder building something that matters.',
    distance: '1.4 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.7258, lng: -74.0126,
    photos: ['https://randomuser.me/api/portraits/men/81.jpg', 'https://randomuser.me/api/portraits/men/82.jpg'],
    height: '5ft 0in', bodyType: 'Athletic', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Relationship'],
    interests: ['Travel', 'Boxing', 'Dancing', 'Baking'],
  },
  {
    id: '67', name: 'Jesse J', age: 31, pronouns: 'she/they',
    identity: 'Genderfluid',
    tagline: 'Wanderlust',
    bio: 'Librarian by day, DJ by night.',
    distance: '2.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7066, lng: -74.004,
    photos: ['https://randomuser.me/api/portraits/women/86.jpg', 'https://randomuser.me/api/portraits/women/87.jpg'],
    height: '6ft 3in', bodyType: 'Petite', ethnicity: 'White',
    lookingFor: ['Friends', 'Dates', 'Networking', 'Relationship'],
    interests: ['Cooking', 'Skateboarding', 'Kayaking'],
  },
  {
    id: '68', name: 'Taylor', age: 29, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Book lover',
    bio: 'Yoga instructor finding peace one pose at a time.',
    distance: '3.9 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.7053, lng: -74.0515,
    photos: ['https://randomuser.me/api/portraits/men/83.jpg', 'https://randomuser.me/api/portraits/men/84.jpg', 'https://randomuser.me/api/portraits/men/85.jpg'],
    height: '5ft 1in', bodyType: 'Muscular', ethnicity: 'Other',
    lookingFor: ['Chat', 'Relationship', 'Friends', 'Dates'],
    interests: ['Dancing', 'Skateboarding', 'Gaming'],
  },
  {
    id: '69', name: 'Ariel', age: 21, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Music lover',
    bio: 'Writer working on my first novel.',
    distance: '0.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.6519, lng: -73.9414,
    photos: ['https://randomuser.me/api/portraits/women/88.jpg', 'https://randomuser.me/api/portraits/women/89.jpg', 'https://randomuser.me/api/portraits/women/90.jpg'],
    height: '6ft 3in', bodyType: 'Petite', ethnicity: 'Middle Eastern',
    lookingFor: ['Chat', 'Right Now', 'Networking', 'Friends'],
    interests: ['Movies', 'Swimming', 'Coffee', 'Foodie'],
  },
  {
    id: '70', name: 'Ellis', age: 26, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Art lover',
    bio: 'Graphic designer with a passion for queer art.',
    distance: '3.9 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.5885, lng: -73.9771,
    photos: ['https://randomuser.me/api/portraits/men/86.jpg', 'https://randomuser.me/api/portraits/men/87.jpg'],
    height: '4ft 10in', bodyType: 'Muscular', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Friends', 'Relationship', 'Dates'],
    interests: ['Hiking', 'Sushi', 'Cats', 'Dogs', 'Painting'],
  },
  {
    id: '71', name: 'Marley', age: 19, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Foodie',
    bio: 'Personal trainer who motivates and makes you laugh.',
    distance: '3.4 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.6302, lng: -73.9401,
    photos: ['https://randomuser.me/api/portraits/women/91.jpg', 'https://randomuser.me/api/portraits/women/92.jpg', 'https://randomuser.me/api/portraits/women/93.jpg'],
    height: '6ft 3in', bodyType: 'Full-figured', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Friends'],
    interests: ['Parties', 'Cosplay', 'Camping', 'Skiing'],
  },
  {
    id: '72', name: 'Parker', age: 23, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Cat lover',
    bio: 'Social worker changing the world one person at a time.',
    distance: '1.1 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.716, lng: -73.9948,
    photos: ['https://randomuser.me/api/portraits/men/88.jpg', 'https://randomuser.me/api/portraits/men/89.jpg', 'https://randomuser.me/api/portraits/men/90.jpg'],
    height: '5ft 9in', bodyType: 'Muscular', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Relationship', 'Right Now', 'Chat', 'Friends'],
    interests: ['Art', 'Fishing', 'Tea', 'Kayaking', 'Baking'],
  },
  {
    id: '73', name: 'Sawyer', age: 18, pronouns: 'she/they',
    identity: 'Genderfluid',
    tagline: 'Dog lover',
    bio: 'DJ spinning beats that make your soul dance.',
    distance: '3.2 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7673, lng: -73.9855,
    photos: ['https://randomuser.me/api/portraits/women/94.jpg', 'https://randomuser.me/api/portraits/women/95.jpg'],
    height: '5ft 3in', bodyType: 'Average', ethnicity: 'Asian',
    lookingFor: ['Right Now', 'Chat'],
    interests: ['Movies', 'Meditation', 'Cycling', 'Theater', 'Camping'],
  },
  {
    id: '74', name: 'Lennox', age: 25, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Beach lover',
    bio: 'Therapist helping people find their inner light.',
    distance: '1.9 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7225, lng: -74.0038,
    photos: ['https://randomuser.me/api/portraits/men/91.jpg', 'https://randomuser.me/api/portraits/men/92.jpg'],
    height: '5ft 5in', bodyType: 'Athletic', ethnicity: 'Middle Eastern',
    lookingFor: ['Networking', 'Dates'],
    interests: ['Coffee', 'Art', 'Tech'],
  },
  {
    id: '75', name: 'Oakley', age: 23, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Mountain lover',
    bio: 'Scientist with glitter in my hair.',
    distance: '4.7 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7676, lng: -73.982,
    photos: ['https://randomuser.me/api/portraits/women/96.jpg', 'https://randomuser.me/api/portraits/women/97.jpg'],
    height: '5ft 4in', bodyType: 'Athletic', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Relationship', 'Chat'],
    interests: ['Photography', 'Boxing', 'Running', 'Tech'],
  },
  {
    id: '76', name: 'Arden', age: 25, pronouns: 'they/them',
    identity: 'Agender',
    tagline: 'City explorer',
    bio: 'Firefighter who rescues cats and hearts.',
    distance: '5.1 mi', lastActive: '5m ago', verified: false, online: false,
    lat: 40.7513, lng: -73.9914,
    photos: ['https://randomuser.me/api/portraits/men/93.jpg', 'https://randomuser.me/api/portraits/men/94.jpg'],
    height: '5ft 11in', bodyType: 'Curvy', ethnicity: 'Asian',
    lookingFor: ['Relationship', 'Right Now', 'Chat'],
    interests: ['Yoga', 'Karaoke', 'Hiking'],
  },
  {
    id: '77', name: 'Shiloh', age: 32, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Sunrise person',
    bio: 'Pilot who has been everywhere but still looking for home.',
    distance: '2.3 mi', lastActive: '1h ago', verified: false, online: false,
    lat: 40.7912, lng: -73.9857,
    photos: ['https://randomuser.me/api/portraits/women/98.jpg', 'https://randomuser.me/api/portraits/women/99.jpg'],
    height: '5ft 3in', bodyType: 'Curvy', ethnicity: 'Middle Eastern',
    lookingFor: ['Friends', 'Right Now'],
    interests: ['Coffee', 'Camping', 'Surfing', 'Yoga', 'Karaoke'],
  },
  {
    id: '78', name: 'Zion', age: 27, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Moon child',
    bio: 'Barber who gives the best conversations with every cut.',
    distance: '4.0 mi', lastActive: '1m ago', verified: true, online: false,
    lat: 40.751, lng: -73.9693,
    photos: ['https://randomuser.me/api/portraits/men/95.jpg', 'https://randomuser.me/api/portraits/men/96.jpg'],
    height: '6ft 2in', bodyType: 'Average', ethnicity: 'Black',
    lookingFor: ['Relationship', 'Dates', 'Networking'],
    interests: ['Parties', 'Tech', 'Swimming'],
  },
  {
    id: '79', name: 'Hayden', age: 25, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Star gazer',
    bio: 'Journalist telling stories that need to be heard.',
    distance: '0.5 mi', lastActive: '5h ago', verified: true, online: false,
    lat: 40.7647, lng: -73.9864,
    photos: ['https://randomuser.me/api/portraits/women/100.jpg', 'https://randomuser.me/api/portraits/women/101.jpg'],
    height: '5ft 9in', bodyType: 'Curvy', ethnicity: 'Other',
    lookingFor: ['Right Now', 'Dates'],
    interests: ['Writing', 'Anime', 'Cosplay', 'Painting', 'Dancing'],
  },
  {
    id: '80', name: 'Robin', age: 29, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Rain lover',
    bio: 'Astronomy nerd looking for my star alignment.',
    distance: '3.4 mi', lastActive: '2h ago', verified: true, online: false,
    lat: 40.7581, lng: -73.9832,
    photos: ['https://randomuser.me/api/portraits/men/97.jpg', 'https://randomuser.me/api/portraits/men/98.jpg'],
    height: '6ft 3in', bodyType: 'Petite', ethnicity: 'Mixed',
    lookingFor: ['Dates', 'Relationship', 'Friends'],
    interests: ['Fitness', 'Skiing', 'Tattoos', 'Theater'],
  },
  {
    id: '81', name: 'Kendall', age: 26, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Snow lover',
    bio: 'Botanical illustrator who sees beauty in every petal.',
    distance: '4.5 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7665, lng: -73.9714,
    photos: ['https://randomuser.me/api/portraits/women/102.jpg', 'https://randomuser.me/api/portraits/women/103.jpg'],
    height: '6ft 5in', bodyType: 'Average', ethnicity: 'Black',
    lookingFor: ['Chat', 'Networking', 'Right Now', 'Friends'],
    interests: ['Gaming', 'Skiing', 'Cooking', 'Foodie'],
  },
  {
    id: '82', name: 'Eden', age: 26, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Spring child',
    bio: 'Former figure skater, current ice cream enthusiast.',
    distance: '0.7 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7436, lng: -73.9924,
    photos: ['https://randomuser.me/api/portraits/men/99.jpg', 'https://randomuser.me/api/portraits/men/100.jpg'],
    height: '5ft 2in', bodyType: 'Athletic', ethnicity: 'Mixed',
    lookingFor: ['Relationship', 'Right Now', 'Dates', 'Networking'],
    interests: ['Parties', 'Pilates', 'Anime', 'Fashion', 'Rock Climbing'],
  },
  {
    id: '83', name: 'Jamie', age: 18, pronouns: 'they/them',
    identity: 'Two-Spirit',
    tagline: 'Summer vibes',
    bio: 'Yoga teacher and former wrestler.',
    distance: '2.9 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.744, lng: -73.9945,
    photos: ['https://randomuser.me/api/portraits/women/104.jpg', 'https://randomuser.me/api/portraits/women/105.jpg', 'https://randomuser.me/api/portraits/women/106.jpg'],
    height: '4ft 11in', bodyType: 'Athletic', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Dates', 'Relationship', 'Chat'],
    interests: ['Wine', 'Surfing', 'Meditation', 'Tech', 'Yoga'],
  },
  {
    id: '84', name: 'Lane', age: 19, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Autumn leaves',
    bio: 'Tour guide who knows every hidden gem.',
    distance: '1.4 mi', lastActive: 'Yesterday', verified: true, online: false,
    lat: 40.7474, lng: -73.9955,
    photos: ['https://randomuser.me/api/portraits/men/101.jpg', 'https://randomuser.me/api/portraits/men/102.jpg'],
    height: '4ft 10in', bodyType: 'Athletic', ethnicity: 'Other',
    lookingFor: ['Dates', 'Right Now'],
    interests: ['Tattoos', 'DJing', 'Travel'],
  },
  {
    id: '85', name: 'Remi', age: 31, pronouns: 'she/they',
    identity: 'Genderfluid',
    tagline: 'Winter wonderland',
    bio: 'Chaotic neutral energy with a heart of gold.',
    distance: '0.9 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7613, lng: -73.9609,
    photos: ['https://randomuser.me/api/portraits/women/107.jpg', 'https://randomuser.me/api/portraits/women/108.jpg', 'https://randomuser.me/api/portraits/women/109.jpg'],
    height: '5ft 2in', bodyType: 'Curvy', ethnicity: 'Mixed',
    lookingFor: ['Dates', 'Networking'],
    interests: ['Coffee', 'Hiking', 'Fitness', 'Photography'],
  },
  {
    id: '86', name: 'Atlas', age: 23, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Spring chicken',
    bio: 'Ceramic artist making beautiful things with my hands.',
    distance: '2.0 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7566, lng: -74.0053,
    photos: ['https://randomuser.me/api/portraits/men/103.jpg', 'https://randomuser.me/api/portraits/men/104.jpg', 'https://randomuser.me/api/portraits/men/105.jpg'],
    height: '4ft 10in', bodyType: 'Muscular', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Right Now', 'Chat', 'Friends'],
    interests: ['Karaoke', 'Skiing', 'Music'],
  },
  {
    id: '87', name: 'Blaze', age: 28, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Summer child',
    bio: 'Swim coach who makes waves.',
    distance: '4.7 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7284, lng: -74.0086,
    photos: ['https://randomuser.me/api/portraits/women/110.jpg', 'https://randomuser.me/api/portraits/women/111.jpg', 'https://randomuser.me/api/portraits/women/112.jpg'],
    height: '5ft 11in', bodyType: 'Curvy', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Friends', 'Chat', 'Relationship'],
    interests: ['Karaoke', 'Tea', 'Sushi', 'Cooking', 'Photography'],
  },
  {
    id: '88', name: 'Cypress', age: 29, pronouns: 'they/them',
    identity: 'Agender',
    tagline: 'Autumn soul',
    bio: 'Radio host with a voice for midnight.',
    distance: '3.5 mi', lastActive: '3h ago', verified: true, online: false,
    lat: 40.6993, lng: -73.9825,
    photos: ['https://randomuser.me/api/portraits/men/106.jpg', 'https://randomuser.me/api/portraits/men/107.jpg'],
    height: '4ft 10in', bodyType: 'Muscular', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Right Now', 'Relationship'],
    interests: ['DJing', 'Anime', 'Karaoke'],
  },
  {
    id: '89', name: 'Dara', age: 25, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Winter baby',
    bio: 'Sommelier who knows wine and vibes.',
    distance: '1.2 mi', lastActive: 'Yesterday', verified: false, online: false,
    lat: 40.7091, lng: -74.0443,
    photos: ['https://randomuser.me/api/portraits/women/113.jpg', 'https://randomuser.me/api/portraits/women/114.jpg', 'https://randomuser.me/api/portraits/women/115.jpg'],
    height: '5ft 1in', bodyType: 'Slim', ethnicity: 'Black',
    lookingFor: ['Networking', 'Dates'],
    interests: ['Brunch', 'Fashion', 'Baking', 'Tattoos', 'Boxing'],
  },
  {
    id: '90', name: 'Fable', age: 21, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Spring dreamer',
    bio: 'Dance instructor who makes everyone feel like a star.',
    distance: '5.0 mi', lastActive: '5m ago', verified: true, online: false,
    lat: 40.6749, lng: -73.958,
    photos: ['https://randomuser.me/api/portraits/men/108.jpg', 'https://randomuser.me/api/portraits/men/109.jpg'],
    height: '5ft 6in', bodyType: 'Curvy', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Friends'],
    interests: ['Tea', 'Swimming', 'Sushi'],
  },
  {
    id: '91', name: 'Juniper', age: 26, pronouns: 'they/them',
    identity: 'Two-Spirit',
    tagline: 'Summer dreamer',
    bio: 'Massage therapist with healing hands.',
    distance: '0.4 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7701, lng: -73.9545,
    photos: ['https://randomuser.me/api/portraits/women/116.jpg', 'https://randomuser.me/api/portraits/women/117.jpg', 'https://randomuser.me/api/portraits/women/118.jpg'],
    height: '4ft 10in', bodyType: 'Athletic', ethnicity: 'Mixed',
    lookingFor: ['Right Now', 'Friends', 'Dates', 'Chat'],
    interests: ['Poetry', 'Photography', 'Skateboarding'],
  },
  {
    id: '92', name: 'Kit', age: 22, pronouns: 'he/she',
    identity: 'Genderfluid',
    tagline: 'Autumn dreamer',
    bio: 'Personal chef cooking love into every meal.',
    distance: '3.5 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7907, lng: -73.9408,
    photos: ['https://randomuser.me/api/portraits/men/110.jpg', 'https://randomuser.me/api/portraits/men/111.jpg', 'https://randomuser.me/api/portraits/men/112.jpg'],
    height: '5ft 7in', bodyType: 'Full-figured', ethnicity: 'Black',
    lookingFor: ['Networking', 'Relationship', 'Right Now'],
    interests: ['Kayaking', 'Photography', 'Hiking'],
  },
  {
    id: '93', name: 'Lake', age: 27, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Winter dreamer',
    bio: 'Dog trainer who listens better than most people.',
    distance: '1.3 mi', lastActive: 'Online now', verified: true, online: true,
    lat: 40.7605, lng: -73.9794,
    photos: ['https://randomuser.me/api/portraits/women/119.jpg', 'https://randomuser.me/api/portraits/women/120.jpg'],
    height: '5ft 2in', bodyType: 'Full-figured', ethnicity: 'Asian',
    lookingFor: ['Networking', 'Chat'],
    interests: ['Surfing', 'Cooking', 'Meditation', 'Dogs', 'DJing'],
  },
  {
    id: '94', name: 'Onyx', age: 20, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Spring lover',
    bio: 'Bookstore owner surrounded by stories.',
    distance: '1.8 mi', lastActive: 'Yesterday', verified: true, online: false,
    lat: 40.763, lng: -73.981,
    photos: ['https://randomuser.me/api/portraits/men/113.jpg', 'https://randomuser.me/api/portraits/men/114.jpg'],
    height: '5ft 0in', bodyType: 'Petite', ethnicity: 'Middle Eastern',
    lookingFor: ['Networking', 'Right Now', 'Dates'],
    interests: ['Swimming', 'Art', 'Painting'],
  },
  {
    id: '95', name: 'Peyton', age: 22, pronouns: 'she/they',
    identity: 'Genderfluid',
    tagline: 'Summer lover',
    bio: 'Music teacher who believes everyone deserves to sing.',
    distance: '2.9 mi', lastActive: '2h ago', verified: true, online: false,
    lat: 40.7498, lng: -73.9849,
    photos: ['https://randomuser.me/api/portraits/women/121.jpg', 'https://randomuser.me/api/portraits/women/122.jpg', 'https://randomuser.me/api/portraits/women/123.jpg'],
    height: '6ft 4in', bodyType: 'Curvy', ethnicity: 'Hispanic/Latina',
    lookingFor: ['Dates', 'Friends', 'Chat'],
    interests: ['Dancing', 'Music', 'Dogs'],
  },
  {
    id: '96', name: 'Rebel', age: 19, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Autumn lover',
    bio: 'Veterinarian in training. My patients are furry.',
    distance: '2.6 mi', lastActive: '15m ago', verified: true, online: false,
    lat: 40.7391, lng: -74.011,
    photos: ['https://randomuser.me/api/portraits/men/115.jpg', 'https://randomuser.me/api/portraits/men/116.jpg'],
    height: '4ft 11in', bodyType: 'Average', ethnicity: 'Middle Eastern',
    lookingFor: ['Dates', 'Friends', 'Networking', 'Relationship'],
    interests: ['Writing', 'Fishing', 'Rock Climbing', 'Craft Beer', 'Anime'],
  },
  {
    id: '97', name: 'Storm', age: 20, pronouns: 'they/them',
    identity: 'Two-Spirit',
    tagline: 'Winter lover',
    bio: 'Social media manager who actually goes outside.',
    distance: '4.3 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.7189, lng: -73.8084,
    photos: ['https://randomuser.me/api/portraits/women/124.jpg', 'https://randomuser.me/api/portraits/women/125.jpg', 'https://randomuser.me/api/portraits/women/126.jpg'],
    height: '5ft 11in', bodyType: 'Curvy', ethnicity: 'Mixed',
    lookingFor: ['Dates', 'Friends'],
    interests: ['Movies', 'Sushi', 'Rock Climbing', 'Pilates', 'Martial Arts'],
  },
  {
    id: '98', name: 'Tatum', age: 29, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Live laugh lip sync',
    bio: 'Architect designing spaces where everyone belongs.',
    distance: '4.6 mi', lastActive: 'Online now', verified: false, online: true,
    lat: 40.6973, lng: -74.0052,
    photos: ['https://randomuser.me/api/portraits/men/117.jpg', 'https://randomuser.me/api/portraits/men/118.jpg'],
    height: '5ft 10in', bodyType: 'Slim', ethnicity: 'White',
    lookingFor: ['Networking', 'Relationship', 'Right Now', 'Dates'],
    interests: ['Painting', 'Running', 'Reading', 'Music'],
  },
  {
    id: '99', name: 'Val', age: 31, pronouns: 'ze/zir',
    identity: 'Genderqueer',
    tagline: 'Soft boi energy',
    bio: 'Marine biologist who talks to fish.',
    distance: '1.6 mi', lastActive: 'Yesterday', verified: true, online: false,
    lat: 40.7374, lng: -74.0044,
    photos: ['https://randomuser.me/api/portraits/women/127.jpg', 'https://randomuser.me/api/portraits/women/128.jpg', 'https://randomuser.me/api/portraits/women/129.jpg'],
    height: '5ft 6in', bodyType: 'Average', ethnicity: 'Middle Eastern',
    lookingFor: ['Networking', 'Right Now', 'Chat', 'Friends'],
    interests: ['Poetry', 'Cats', 'Fashion'],
  },
  {
    id: '100', name: 'Sage V', age: 20, pronouns: 'they/them',
    identity: 'Non-Binary',
    tagline: 'Bookworm with a wild side',
    bio: 'Electrician who lights up rooms and spirits.',
    distance: '1.5 mi', lastActive: '15m ago', verified: false, online: false,
    lat: 40.7631, lng: -74.0046,
    photos: ['https://randomuser.me/api/portraits/men/119.jpg', 'https://randomuser.me/api/portraits/men/120.jpg'],
    height: '5ft 11in', bodyType: 'Slim', ethnicity: 'Middle Eastern',
    lookingFor: ['Right Now', 'Chat'],
    interests: ['Travel', 'Rock Climbing', 'Fishing', 'Skateboarding'],
  },
  {
    id: '101', name: 'Kai K', age: 30, pronouns: 'they/them',
    identity: 'Agender',
    tagline: 'Gym rat in denial',
    bio: 'City girl with a country heart. Love brunch and long walks to the fridge.',
    distance: '0.1 mi', lastActive: '1m ago', verified: true, online: false,
    lat: 40.8013, lng: -73.9473,
    photos: ['https://randomuser.me/api/portraits/women/130.jpg', 'https://randomuser.me/api/portraits/women/131.jpg'],
    height: '6ft 2in', bodyType: 'Average', ethnicity: 'Middle Eastern',
    lookingFor: ['Right Now', 'Friends'],
    interests: ['Surfing', 'Coffee', 'Painting', 'Swimming'],
  },
];

export default profiles;
export const ME_ID = 'me';
export const ME = {
  id: ME_ID,
  name: 'You',
  age: 25,
  pronouns: 'they/them',
  identity: 'Trans Person',
  tagline: 'New here! Lets chat',
  bio: 'Just downloaded Chasr. Looking for genuine connections.',
  distance: '--',
  lastActive: 'Online now',
  verified: true,
  online: true,
  last_active: 0,
  lat: 40.7306,
  lng: -73.9866,
  photos: ['https://randomuser.me/api/portraits/women/0.jpg'],
  height: '5ft 7in',
  bodyType: 'Average',
  body_type: 'Average',
  ethnicity: 'Mixed',
  lookingFor: ['Chat', 'Friends', 'Dates'],
  looking_for: ['Chat', 'Friends', 'Dates'],
  interests: ['Coffee', 'Music', 'Hiking'],
};
